# Forge
name: Lighter
author: pradador
category: Interface
tags: [parser, syntax highlighter]
demo: http://pradador.com/code/lighterjs/demo/
current: 2.1

# Packager
license: "MIT License"
exports: "Lighter.js"
sources:
  - "Source/Lighter.js"
  - "Source/Loader.js"
  - "Source/Compiler.js"
  - "Source/Compiler/Inline.js"
  - "Source/Compiler/List.js"
  - "Source/Compiler/Lines.js"
  - "Source/Wick.js"
  - "Source/Fuel.js"
  - "Source/Parser.js"
  - "Source/Parser/Lazy.js"
  - "Source/Parser/Smart.js"
